### ISSUE TITLE
Questions about the DyNeRF dataset.

### ISSUE THREAD

**Issue by 08119106** [wuminye/TeTriRF#1]
Dear author, hello. I am trying to reproduce the method on the DyNeRF dataset based on the readme document you provided.

I’m encountering an issue where I am unable to reproduce the metrics for the DyNeRF dataset as specified in your paper, using the configuration files you provided.

In your paper, you detailed the training specifics for the NHR dataset, but I did not see relevant training details for the DyNeRF dataset.

I hope you can provide me with some assistance on this matter. I would greatly appreciate it!

**Comment by wuminye** [comment]
The training process of DyNeRF is almost the same as that of NHR, except that DyNeRF first reconstructs the initial frame. The relevant training strategy is written in the ’gen_n3d.py‘ file. If you can provide more detailed information, such as your operational procedure and the phenomena you have observed so far, I might be able to assist you better.

**Comment by 08119106** [comment]
Thank you very much for responding to my question! I used the “sear_steak” scene in the DyNeRF dataset as an example to illustrate the issue I encountered more clearly. 

In the “configs/N3D/sear_steak” file, you provided the training parameter configurations for reconstructing the “sear_steak” scene, where you performed 3x downsampling on the data. However, I currently intend to train at the original resolution. When I adjusted the factor to 1 and trained the first frame of this scene, the final test PSNR was around 32dB.

What I want to ask is, when I want to train at the original resolution, is it sufficient to adjust only the factor? And which settings in “sear_steak.py” can I adjust to achieve a better test PSNR during training?

Once again, thank you for being able to answer my questions.

**Comment by wuminye** [comment]
It should be possible to adjust only the factor. However, different resolutions may require different optimization parameters to achieve better results. For example, num_voxels, mpi_depth, and weight_tv_density might need to be adjusted.

**Comment by 08119106** [comment]
Thank you for your response. Currently, I am unable to reproduce the metrics for the "sear_steak" scene as provided in your paper at the original resolution. I would like to ask if the results presented in your paper were obtained at the original resolution during training.

**Comment by wuminye** [comment]
I use the factor in the configuration files to downscale the training images.

**Comment by 08119106** [comment]
Sure, I understand. Thank you very much for answering my questions!
